import type { Metadata } from "next"
import Link from "next/link"
import { DeepHero, CrossLinkFooter, DeepSection } from "@/components/DeepShell"

export const metadata: Metadata = {
  title: "Terms of Service · Sigilix",
  description:
    "Terms governing use of Sigilix — what we provide, what we expect of you, and the limits on both sides.",
}

export default function TermsPage() {
  return (
    <>
      <DeepHero
        kicker="Terms of Service"
        title={
          <>
            Terms of Service. <span className="text-accent">No legalese where we can avoid it.</span>
          </>
        }
        lead={
          <>
            By using Sigilix you agree to these terms. They cover what we provide, what we expect
            of you, and the limits on both sides. If anything below is unclear, email{" "}
            <a
              href="mailto:support@arcanchor.com"
              className="text-text-primary hover:text-accent transition-colors underline-offset-4 hover:underline"
            >
              support@arcanchor.com
            </a>{" "}
            before you proceed.
          </>
        }
      />

      <DeepSection number="01" kicker="Effective" title={<>Effective date: May 5, 2026.</>}>
        <p className="text-text-secondary leading-relaxed max-w-3xl">
          Sigilix is operated by <strong className="text-text-primary">Arc and Anchor LLC</strong>,
          a US company. These Terms govern access to and use of the Sigilix service, marketing
          site, and APIs.
        </p>
      </DeepSection>

      <DeepSection number="02" kicker="The service" title={<>What you get.</>}>
        <p className="text-text-secondary leading-relaxed max-w-3xl">
          Sigilix runs an automated, ensemble-based code review against pull requests on
          repositories where you have installed our GitHub App. Reviews include findings, severity
          ratings, and a verdict. The service is provided on a tiered basis (Free, Pro, Max,
          Enterprise) — see <Link href="/pricing" className="text-text-primary hover:text-accent transition-colors underline-offset-4 hover:underline">/pricing</Link>.
        </p>
      </DeepSection>

      <DeepSection number="03" kicker="Your account" title={<>Eligibility, security, billing.</>}>
        <ul className="space-y-3 text-text-secondary leading-relaxed max-w-3xl">
          {[
            "You must be at least 18 and authorized to install GitHub Apps on the repositories you connect.",
            "You are responsible for the actions taken under your account, including those of your team members on shared seats.",
            "Notify us promptly at security@arcanchor.com if you suspect unauthorized access.",
            "Paid plans are billed monthly in arrears via the payment processor on file. Failure to pay results in suspension after the grace period documented in /pricing.",
            "You may cancel or downgrade at any time; refunds are evaluated case-by-case (see Privacy and Billing for the policy summary).",
          ].map((line) => (
            <li key={line} className="flex gap-3">
              <span className="text-accent mt-1">·</span>
              <span>{line}</span>
            </li>
          ))}
        </ul>
      </DeepSection>

      <DeepSection number="04" kicker="Acceptable use" title={<>What you cannot do.</>}>
        <ul className="space-y-3 text-text-secondary leading-relaxed max-w-3xl">
          {[
            "Do not use Sigilix to review code that you do not have the right to share with us. You represent that you have all necessary rights to the code we review on your behalf.",
            "Do not attempt to extract our system prompts, model selection logic, or proprietary scoring weights via prompt injection or reverse engineering.",
            "Do not use Sigilix to generate, refine, or distribute malware, exploit chains, or content that violates GitHub's Acceptable Use Policies.",
            "Do not exceed the rate limits of your tier or attempt to circumvent them. Unlimited tiers (Enterprise) require a written agreement.",
            "Do not resell Sigilix as a service to third parties without an executed reseller agreement.",
          ].map((line) => (
            <li key={line} className="flex gap-3">
              <span className="text-accent mt-1">·</span>
              <span>{line}</span>
            </li>
          ))}
        </ul>
      </DeepSection>

      <DeepSection number="05" kicker="Output" title={<>The review is information, not advice.</>}>
        <p className="text-text-secondary leading-relaxed max-w-3xl">
          Sigilix findings are best-effort signal generated by language models. They are not
          legally binding security clearance, regulatory compliance certification, or guaranteed
          coverage of all defects. You retain final authority over what to merge. Rely on the
          findings as one input among many — code review by humans, automated tests, security
          scanning, and your own judgement.
        </p>
      </DeepSection>

      <DeepSection number="06" kicker="Intellectual property" title={<>Who owns what.</>}>
        <ul className="space-y-3 text-text-secondary leading-relaxed max-w-3xl">
          {[
            "You retain all rights to the code you submit. We claim no license to your code beyond what's necessary to run the review and post it back to GitHub.",
            "Sigilix retains all rights to the service itself: the orchestration logic, prompts, scoring, model routing, and the marketing material on sigilix.ai.",
            "Findings posted on your pull requests become part of your repository under your existing GitHub Terms; we make no separate claim on them.",
          ].map((line) => (
            <li key={line} className="flex gap-3">
              <span className="text-accent mt-1">·</span>
              <span>{line}</span>
            </li>
          ))}
        </ul>
      </DeepSection>

      <DeepSection number="07" kicker="Service level" title={<>Best-effort uptime.</>}>
        <p className="text-text-secondary leading-relaxed max-w-3xl">
          We target high availability but do not yet publish a contractual SLA. Status updates and
          incident history are at{" "}
          <Link href="/status" className="text-text-primary hover:text-accent transition-colors underline-offset-4 hover:underline">
            /status
          </Link>
          . Enterprise customers may negotiate a written SLA as part of their order form.
        </p>
      </DeepSection>

      <DeepSection number="08" kicker="Disclaimers" title={<>Limits of liability.</>}>
        <p className="text-text-secondary leading-relaxed max-w-3xl mb-4 uppercase font-mono text-xs tracking-[0.2em] text-text-muted">
          Read this section carefully.
        </p>
        <p className="text-text-secondary leading-relaxed max-w-3xl mb-4">
          The service is provided &quot;as is&quot; without warranty of any kind. To the fullest
          extent permitted by law, Arc and Anchor LLC disclaims all warranties, express or
          implied, including merchantability, fitness for a particular purpose, and
          non-infringement.
        </p>
        <p className="text-text-secondary leading-relaxed max-w-3xl">
          Our aggregate liability for any claim related to the service is limited to the amount
          you paid for the service in the twelve months preceding the claim. We are not liable for
          indirect, consequential, or incidental damages, including lost profits or lost data,
          even if advised of the possibility.
        </p>
      </DeepSection>

      <DeepSection number="09" kicker="Termination" title={<>How either of us can end this.</>}>
        <p className="text-text-secondary leading-relaxed max-w-3xl">
          You may stop using Sigilix at any time by uninstalling the GitHub App and canceling your
          subscription. We may suspend or terminate accounts for material breach of these terms,
          unpaid invoices, or activity that puts our infrastructure or other customers at risk.
          We will give reasonable notice for non-emergency terminations.
        </p>
      </DeepSection>

      <DeepSection number="10" kicker="Governing law" title={<>Where disputes are resolved.</>}>
        <p className="text-text-secondary leading-relaxed max-w-3xl">
          These Terms are governed by the laws of the State of Nevada, USA, without regard to
          conflict-of-laws provisions. Disputes will be resolved in the state or federal courts
          located in Las Vegas, Nevada (Clark County), except where mandated otherwise by your
          local jurisdiction.
        </p>
      </DeepSection>

      <DeepSection number="11" kicker="Changes" title={<>How updates work.</>}>
        <p className="text-text-secondary leading-relaxed max-w-3xl">
          We will revise these Terms as the service evolves. Material changes will be announced by
          email to the billing contact and posted at{" "}
          <Link href="/terms" className="text-text-primary hover:text-accent transition-colors underline-offset-4 hover:underline">
            sigilix.ai/terms
          </Link>{" "}
          with the new effective date. Continued use after a change constitutes acceptance.
        </p>
      </DeepSection>

      <DeepSection number="12" kicker="Contact" title={<>Send the lawyer mail here.</>}>
        <p className="text-text-secondary leading-relaxed max-w-3xl">
          Legal:{" "}
          <a
            href="mailto:legal@arcanchor.com"
            className="text-text-primary hover:text-accent transition-colors underline-offset-4 hover:underline"
          >
            legal@arcanchor.com
          </a>
          . Privacy:{" "}
          <a
            href="mailto:privacy@arcanchor.com"
            className="text-text-primary hover:text-accent transition-colors underline-offset-4 hover:underline"
          >
            privacy@arcanchor.com
          </a>
          .
        </p>
      </DeepSection>

      <CrossLinkFooter
        prev={{ label: "Privacy", href: "/privacy" }}
        next={{ label: "Status", href: "/status" }}
        lastUpdated="2026-05-05"
      />
    </>
  )
}
